; Generated from BUtil installer strings. Product name adapted for Conference Audio Recorder.

LangString Installer_LaunchApp ${LANG_ENGLISH} "Launch App"
LangString Installer_LaunchApp ${LANG_FRENCH} "Lancer l'application"
LangString Installer_LaunchApp ${LANG_GERMAN} "App starten"
LangString Installer_LaunchApp ${LANG_SPANISHINTERNATIONAL} "Iniciar aplicación"
LangString Installer_LaunchApp ${LANG_ITALIAN} "Avvia applicazione"
LangString Installer_LaunchApp ${LANG_PORTUGUESE} "Iniciar aplicativo"
LangString Installer_LaunchApp ${LANG_PORTUGUESEBR} "Iniciar aplicativo"
LangString Installer_LaunchApp ${LANG_RUSSIAN} "Запустить приложение"
LangString Installer_LaunchApp ${LANG_SIMPCHINESE} "启动应用程序"
LangString Installer_LaunchApp ${LANG_TRADCHINESE} "啟動應用程式"
LangString Installer_LaunchApp ${LANG_JAPANESE} "アプリを起動"
LangString Installer_LaunchApp ${LANG_KOREAN} "앱 실행"
LangString Installer_LaunchApp ${LANG_DUTCH} "App starten"
LangString Installer_LaunchApp ${LANG_POLISH} "Uruchom aplikację"
LangString Installer_LaunchApp ${LANG_CZECH} "Spustit aplikaci"
LangString Installer_LaunchApp ${LANG_SWEDISH} "Starta app"
LangString Installer_LaunchApp ${LANG_DANISH} "Start app"
LangString Installer_LaunchApp ${LANG_NORWEGIAN} "Start appen"
LangString Installer_LaunchApp ${LANG_FINNISH} "Käynnistä sovellus"
LangString Installer_LaunchApp ${LANG_GREEK} "Εκκίνηση εφαρμογής"
LangString Installer_LaunchApp ${LANG_HUNGARIAN} "Alkalmazás indítása"
LangString Installer_LaunchApp ${LANG_ROMANIAN} "Lansare aplicație"
LangString Installer_LaunchApp ${LANG_TURKISH} "Uygulamayı Başlat"
LangString Installer_LaunchApp ${LANG_UKRAINIAN} "Запустити програму"
LangString Installer_LaunchApp ${LANG_ARABIC} "تشغيل التطبيق"
LangString Installer_LaunchApp ${LANG_HEBREW} "הפעל אפליקציה"
LangString Installer_LaunchApp ${LANG_THAI} "เปิดแอป"
LangString Installer_LaunchApp ${LANG_VIETNAMESE} "Khởi chạy ứng dụng"
LangString Installer_LaunchApp ${LANG_INDONESIAN} "Jalankan Aplikasi"
LangString Installer_LaunchApp ${LANG_BULGARIAN} "Стартиране на приложението"
LangString Installer_LaunchApp ${LANG_CROATIAN} "Pokreni aplikaciju"
LangString Installer_LaunchApp ${LANG_SLOVAK} "Spustiť aplikáciu"
LangString Installer_LaunchApp ${LANG_SLOVENIAN} "Zaženi aplikacijo"

LangString Installer_ArchRequired ${LANG_ENGLISH} "This installer requires a x64 or arm64 version of Windows."
LangString Installer_ArchRequired ${LANG_FRENCH} "Ce programme d'installation nécessite une version x64 ou arm64 de Windows."
LangString Installer_ArchRequired ${LANG_GERMAN} "Dieses Installationsprogramm erfordert eine x64- oder arm64-Version von Windows."
LangString Installer_ArchRequired ${LANG_SPANISHINTERNATIONAL} "Este instalador requiere una versión x64 o arm64 de Windows."
LangString Installer_ArchRequired ${LANG_ITALIAN} "Questo programma di installazione richiede una versione di Windows a 64bit o ARM64."
LangString Installer_ArchRequired ${LANG_PORTUGUESE} "Este instalador requer uma versão x64 ou arm64 do Windows."
LangString Installer_ArchRequired ${LANG_PORTUGUESEBR} "Este instalador requer uma versão x64 ou arm64 do Windows."
LangString Installer_ArchRequired ${LANG_RUSSIAN} "Для этого установщика требуется версия Windows x64 или arm64."
LangString Installer_ArchRequired ${LANG_SIMPCHINESE} "此安装程序需要 x64 或 arm64 版本的 Windows。"
LangString Installer_ArchRequired ${LANG_TRADCHINESE} "此安裝程式需要 x64 或 arm64 版本的 Windows。"
LangString Installer_ArchRequired ${LANG_JAPANESE} "このインストーラーには x64 または arm64 バージョンの Windows が必要です。"
LangString Installer_ArchRequired ${LANG_KOREAN} "이 설치 프로그램은 x64 또는 arm64 버전의 Windows가 필요합니다."
LangString Installer_ArchRequired ${LANG_DUTCH} "Dit installatieprogramma vereist een x64- of arm64-versie van Windows."
LangString Installer_ArchRequired ${LANG_POLISH} "Ten instalator wymaga wersji x64 lub arm64 systemu Windows."
LangString Installer_ArchRequired ${LANG_CZECH} "Tento instalační program vyžaduje verzi Windows x64 nebo arm64."
LangString Installer_ArchRequired ${LANG_SWEDISH} "Detta installationsprogram kräver en x64- eller arm64-version av Windows."
LangString Installer_ArchRequired ${LANG_DANISH} "Dette installationsprogram kræver en x64- eller arm64-version af Windows."
LangString Installer_ArchRequired ${LANG_NORWEGIAN} "Dette installasjonsprogrammet krever en x64- eller ARM64-versjon av Windows."
LangString Installer_ArchRequired ${LANG_FINNISH} "Tämä asennusohjelma vaatii x64- tai arm64-version Windowsista."
LangString Installer_ArchRequired ${LANG_GREEK} "Αυτό το πρόγραμμα εγκατάστασης απαιτεί έκδοση x64 ή arm64 των Windows."
LangString Installer_ArchRequired ${LANG_HUNGARIAN} "Ez a telepítő a Windows x64 vagy arm64 verziójat igényli."
LangString Installer_ArchRequired ${LANG_ROMANIAN} "Acest program de instalare necesită o versiune x64 sau arm64 de Windows."
LangString Installer_ArchRequired ${LANG_TURKISH} "Bu yükleyici, Windows'un x64 veya arm64 sürümünü gerektirir."
LangString Installer_ArchRequired ${LANG_UKRAINIAN} "Цей інсталятор потребує x64 або arm64 версії Windows."
LangString Installer_ArchRequired ${LANG_ARABIC} "يتطلب هذا المثبت إصداراً من Windows بمعمارية x64 أو arm64."
LangString Installer_ArchRequired ${LANG_HEBREW} "תוכנית התקנה זו דורשת גרסת x64 או arm64 של Windows."
LangString Installer_ArchRequired ${LANG_THAI} "ตัวติดตั้งนี้ต้องการ Windows เวอร์ชัน x64 หรือ arm64"
LangString Installer_ArchRequired ${LANG_VIETNAMESE} "Trình cài đặt này yêu cầu phiên bản Windows x64 hoặc arm64."
LangString Installer_ArchRequired ${LANG_INDONESIAN} "Penginstal ini memerlukan Windows versi x64 atau arm64."
LangString Installer_ArchRequired ${LANG_BULGARIAN} "Този инсталатор изисква x64 или ARM64 версия на Windows."
LangString Installer_ArchRequired ${LANG_CROATIAN} "Ovaj instalacijski program zahtijeva x64 ili ARM64 verziju sustava Windows."
LangString Installer_ArchRequired ${LANG_SLOVAK} "Tento inštalátor vyžaduje x64 alebo ARM64 verziu systému Windows."
LangString Installer_ArchRequired ${LANG_SLOVENIAN} "Ta namestitveni program zahteva x64 ali ARM64 različico sistema Windows."

LangString Installer_InstallModeTitle ${LANG_ENGLISH} "Choose Installation Type"
LangString Installer_InstallModeTitle ${LANG_FRENCH} "Choisir le type d'installation"
LangString Installer_InstallModeTitle ${LANG_GERMAN} "Installationstyp wählen"
LangString Installer_InstallModeTitle ${LANG_SPANISHINTERNATIONAL} "Elija el tipo de instalación"
LangString Installer_InstallModeTitle ${LANG_ITALIAN} "Scegli il tipo di installazione"
LangString Installer_InstallModeTitle ${LANG_PORTUGUESE} "Escolha o tipo de instalação"
LangString Installer_InstallModeTitle ${LANG_PORTUGUESEBR} "Escolha o tipo de instalação"
LangString Installer_InstallModeTitle ${LANG_RUSSIAN} "Выберите тип установки"
LangString Installer_InstallModeTitle ${LANG_SIMPCHINESE} "选择安装类型"
LangString Installer_InstallModeTitle ${LANG_TRADCHINESE} "選擇安裝類型"
LangString Installer_InstallModeTitle ${LANG_JAPANESE} "インストールの種類を選択"
LangString Installer_InstallModeTitle ${LANG_KOREAN} "설치 유형 선택"
LangString Installer_InstallModeTitle ${LANG_DUTCH} "Kies installatietype"
LangString Installer_InstallModeTitle ${LANG_POLISH} "Wybierz typ instalacji"
LangString Installer_InstallModeTitle ${LANG_CZECH} "Zvolte typ instalace"
LangString Installer_InstallModeTitle ${LANG_SWEDISH} "Välj installationstyp"
LangString Installer_InstallModeTitle ${LANG_DANISH} "Vælg installationstype"
LangString Installer_InstallModeTitle ${LANG_NORWEGIAN} "Velg installasjonstype"
LangString Installer_InstallModeTitle ${LANG_FINNISH} "Valitse asennustyyppi"
LangString Installer_InstallModeTitle ${LANG_GREEK} "Επιλογή τύπου εγκατάστασης"
LangString Installer_InstallModeTitle ${LANG_HUNGARIAN} "Telepítés típusának kiválasztása"
LangString Installer_InstallModeTitle ${LANG_ROMANIAN} "Alegeți tipul de instalare"
LangString Installer_InstallModeTitle ${LANG_TURKISH} "Yükleme Türünü Seçin"
LangString Installer_InstallModeTitle ${LANG_UKRAINIAN} "Виберіть тип встановлення"
LangString Installer_InstallModeTitle ${LANG_ARABIC} "اختيار نوع التثبيت"
LangString Installer_InstallModeTitle ${LANG_HEBREW} "בחר סוג התקנה"
LangString Installer_InstallModeTitle ${LANG_THAI} "เลือกประเภทการติดตั้ง"
LangString Installer_InstallModeTitle ${LANG_VIETNAMESE} "Chọn kiểu cài đặt"
LangString Installer_InstallModeTitle ${LANG_INDONESIAN} "Pilih Jenis Instalasi"
LangString Installer_InstallModeTitle ${LANG_BULGARIAN} "Изберете тип на инсталация"
LangString Installer_InstallModeTitle ${LANG_CROATIAN} "Odaberite vrstu instalacije"
LangString Installer_InstallModeTitle ${LANG_SLOVAK} "Vyberte typ inštalácie"
LangString Installer_InstallModeTitle ${LANG_SLOVENIAN} "Izberite vrsto namestitve"

LangString Installer_InstallModeSubtitle ${LANG_ENGLISH} "Select who can use this application"
LangString Installer_InstallModeSubtitle ${LANG_FRENCH} "Sélectionnez qui peut utiliser cette application"
LangString Installer_InstallModeSubtitle ${LANG_GERMAN} "Wählen Sie aus, wer diese Anwendung verwenden kann"
LangString Installer_InstallModeSubtitle ${LANG_SPANISHINTERNATIONAL} "Seleccione quién puede utilizar esta aplicación"
LangString Installer_InstallModeSubtitle ${LANG_ITALIAN} "Seleziona chi può usare questa applicazione"
LangString Installer_InstallModeSubtitle ${LANG_PORTUGUESE} "Selecione quem pode usar este aplicativo"
LangString Installer_InstallModeSubtitle ${LANG_PORTUGUESEBR} "Selecione quem pode usar este aplicativo"
LangString Installer_InstallModeSubtitle ${LANG_RUSSIAN} "Выберите, кто сможет использовать это приложение"
LangString Installer_InstallModeSubtitle ${LANG_SIMPCHINESE} "选择谁可以使用此应用程序"
LangString Installer_InstallModeSubtitle ${LANG_TRADCHINESE} "選擇誰可以使用此應用程式"
LangString Installer_InstallModeSubtitle ${LANG_JAPANESE} "このアプリケーションを使用できるユーザーを選択"
LangString Installer_InstallModeSubtitle ${LANG_KOREAN} "이 응용 프로그램을 사용할 수 있는 대상 선택"
LangString Installer_InstallModeSubtitle ${LANG_DUTCH} "Selecteer wie deze toepassing kan gebruiken"
LangString Installer_InstallModeSubtitle ${LANG_POLISH} "Wybierz, kto może korzystać z tej aplikacji"
LangString Installer_InstallModeSubtitle ${LANG_CZECH} "Vyberte, kdo může tuto aplikaci používat"
LangString Installer_InstallModeSubtitle ${LANG_SWEDISH} "Välj vem som kan använda denna applikation"
LangString Installer_InstallModeSubtitle ${LANG_DANISH} "Vælg hvem der kan bruge denne applikation"
LangString Installer_InstallModeSubtitle ${LANG_NORWEGIAN} "Velg hvem som kan bruke denne applikasjonen"
LangString Installer_InstallModeSubtitle ${LANG_FINNISH} "Valitse, kuka voi käyttää tätä sovellusta"
LangString Installer_InstallModeSubtitle ${LANG_GREEK} "Επιλέξτε ποιος μπορεί να χρησιμοποιήσει αυτήν την εφαρμογή"
LangString Installer_InstallModeSubtitle ${LANG_HUNGARIAN} "Válassza ki, ki használhatja ezt az alkalmazást"
LangString Installer_InstallModeSubtitle ${LANG_ROMANIAN} "Selectați cine poate folosi această aplicație"
LangString Installer_InstallModeSubtitle ${LANG_TURKISH} "Bu uygulamayı kimin kullanabileceğini seçin"
LangString Installer_InstallModeSubtitle ${LANG_UKRAINIAN} "Виберіть, хто зможе використовувати цю програму"
LangString Installer_InstallModeSubtitle ${LANG_ARABIC} "حدد من يمكنه استخدام هذا التطبيق"
LangString Installer_InstallModeSubtitle ${LANG_HEBREW} "בחר מי יכול להשתמש באפליקציה זו"
LangString Installer_InstallModeSubtitle ${LANG_THAI} "เลือกว่าใครสามารถใช้แอปพลิเคชันนี้ได้"
LangString Installer_InstallModeSubtitle ${LANG_VIETNAMESE} "Chọn ai có thể sử dụng ứng dụng này"
LangString Installer_InstallModeSubtitle ${LANG_INDONESIAN} "Pilih siapa yang dapat menggunakan aplikasi ini"
LangString Installer_InstallModeSubtitle ${LANG_BULGARIAN} "Изберете кой може да използва това приложение"
LangString Installer_InstallModeSubtitle ${LANG_CROATIAN} "Odaberite tko može koristiti ovu aplikaciju"
LangString Installer_InstallModeSubtitle ${LANG_SLOVAK} "Vyberte, kto môže používať túto aplikáciu"
LangString Installer_InstallModeSubtitle ${LANG_SLOVENIAN} "Izberite, kdo lahko uporablja to aplikacijo"

LangString Installer_InstallModeDescription ${LANG_ENGLISH} "Please choose whether you want to install Conference Audio Recorder for yourself only or for all users of this computer."
LangString Installer_InstallModeDescription ${LANG_FRENCH} "Veuillez choisir si vous souhaitez installer Conference Audio Recorder uniquement pour vous ou pour tous les utilisateurs de cet ordinateur."
LangString Installer_InstallModeDescription ${LANG_GERMAN} "Bitte wählen Sie, ob Sie Conference Audio Recorder nur für sich selbst oder für alle Benutzer dieses Computers installieren möchten."
LangString Installer_InstallModeDescription ${LANG_SPANISHINTERNATIONAL} "Elija si desea instalar Conference Audio Recorder solo para usted o para todos los usuarios de esta computadora."
LangString Installer_InstallModeDescription ${LANG_ITALIAN} "Scegli se installare Conference Audio Recorder solo per l'utente attuale o per tutti gli utenti di questo computer."
LangString Installer_InstallModeDescription ${LANG_PORTUGUESE} "Escolha se deseja instalar o Conference Audio Recorder apenas para você ou para todos os usuários deste computador."
LangString Installer_InstallModeDescription ${LANG_PORTUGUESEBR} "Escolha se deseja instalar o Conference Audio Recorder somente para você ou para todos os usuários deste computador."
LangString Installer_InstallModeDescription ${LANG_RUSSIAN} "Выберите, установить Conference Audio Recorder только для себя или для всех пользователей этого компьютера."
LangString Installer_InstallModeDescription ${LANG_SIMPCHINESE} "请选择您是仅为自己安装 Conference Audio Recorder 还是为此计算机的所有用户安装。"
LangString Installer_InstallModeDescription ${LANG_TRADCHINESE} "請選擇您要僅為自己安裝 Conference Audio Recorder，還是為此電腦上的所有使用者安裝。"
LangString Installer_InstallModeDescription ${LANG_JAPANESE} "Conference Audio Recorder を自分だけにインストールするか、このコンピューターのすべてのユーザー向けにインストールするかを選択してください。"
LangString Installer_InstallModeDescription ${LANG_KOREAN} "Conference Audio Recorder을 자신만을 위해 설치할지 또는 이 컴퓨터의 모든 사용자를 위해 설치할지 선택하세요."
LangString Installer_InstallModeDescription ${LANG_DUTCH} "Kies of u Conference Audio Recorder alleen voor uzelf of voor alle gebruikers van deze computer wilt installeren."
LangString Installer_InstallModeDescription ${LANG_POLISH} "Wybierz, czy chcesz zainstalować Conference Audio Recorder tylko dla siebie, czy dla wszystkich użytkowników tego komputera."
LangString Installer_InstallModeDescription ${LANG_CZECH} "Vyberte prosím, zda chcete nainstalovat Conference Audio Recorder pouze pro sebe nebo pro všechny uživatele tohoto počítače."
LangString Installer_InstallModeDescription ${LANG_SWEDISH} "Välj om du vill installera Conference Audio Recorder enbart för dig själv eller för alla användare på denna dator."
LangString Installer_InstallModeDescription ${LANG_DANISH} "Vælg venligst, om du vil installere Conference Audio Recorder kun for dig selv eller for alle brugere af denne computer."
LangString Installer_InstallModeDescription ${LANG_NORWEGIAN} "Velg om du vil installere Conference Audio Recorder bare for deg selv eller for alle brukere av denne datamaskinen."
LangString Installer_InstallModeDescription ${LANG_FINNISH} "Valitse, haluatko asentaa Conference Audio Recorder vain itsellesi vai kaikille tämän tietokoneen käyttäjille."
LangString Installer_InstallModeDescription ${LANG_GREEK} "Επιλέξτε εάν θέλετε να εγκαταστήσετε το Conference Audio Recorder μόνο για εσάς ή για όλους τους χρήστες αυτού του υπολογιστή."
LangString Installer_InstallModeDescription ${LANG_HUNGARIAN} "Kérjük, válassza ki, hogy a Conference Audio Recorder-t csak saját magának vagy a számítógép összes felhasználójának szeretné telepíteni."
LangString Installer_InstallModeDescription ${LANG_ROMANIAN} "Vă rugăm să alegeți dacă doriți să instalați Conference Audio Recorder doar pentru dvs. sau pentru toți utilizatorii acestui computer."
LangString Installer_InstallModeDescription ${LANG_TURKISH} "Conference Audio Recorder'i yalnızca kendiniz için mi yoksa bu bilgisayarın tüm kullanıcıları için mi yüklemek istediğinizi seçin."
LangString Installer_InstallModeDescription ${LANG_UKRAINIAN} "Виберіть, чи хочете ви встановити Conference Audio Recorder лише для себе або для всіх користувачів цього комп'ютера."
LangString Installer_InstallModeDescription ${LANG_ARABIC} "يرجى اختيار ما إذا كنت تريد تثبيت Conference Audio Recorder لنفسك فقط أو لجميع مستخدمي هذا الكمبيوتر."
LangString Installer_InstallModeDescription ${LANG_HEBREW} "בחר אם ברצונך להתקין את Conference Audio Recorder עבורך בלבד או עבור כל משתמשי מחשב זה."
LangString Installer_InstallModeDescription ${LANG_THAI} "กรุณาเลือกว่าคุณต้องการติดตั้ง Conference Audio Recorder สำหรับตัวคุณเองเท่านั้นหรือสำหรับผู้ใช้ทุกคนบนคอมพิวเตอร์เครื่องนี้"
LangString Installer_InstallModeDescription ${LANG_VIETNAMESE} "Vui lòng chọn bạn muốn cài đặt Conference Audio Recorder chỉ cho mình hay cho tất cả người dùng của máy tính này."
LangString Installer_InstallModeDescription ${LANG_INDONESIAN} "Silakan pilih apakah Anda ingin menginstal Conference Audio Recorder hanya untuk diri sendiri atau untuk semua pengguna komputer ini."
LangString Installer_InstallModeDescription ${LANG_BULGARIAN} "Моля, изберете дали искате да инсталирате Conference Audio Recorder само за себе си или за всички потребители на този компютър."
LangString Installer_InstallModeDescription ${LANG_CROATIAN} "Molimo odaberite želite li instalirati Conference Audio Recorder samo za sebe ili za sve korisnike ovog računala."
LangString Installer_InstallModeDescription ${LANG_SLOVAK} "Vyberte prosím, či chcete nainštalovať Conference Audio Recorder iba pre seba alebo pre všetkých používateľov tohto počítača."
LangString Installer_InstallModeDescription ${LANG_SLOVENIAN} "Prosimo, izberite, ali želite namestiti Conference Audio Recorder samo zase ali za vse uporabnike tega računalnika."

LangString Installer_CurrentUserOption ${LANG_ENGLISH} "Install for &current user only"
LangString Installer_CurrentUserOption ${LANG_FRENCH} "Installer pour l'utilisateur a&ctuel uniquement"
LangString Installer_CurrentUserOption ${LANG_GERMAN} "Nur für a&ktuellen Benutzer installieren"
LangString Installer_CurrentUserOption ${LANG_SPANISHINTERNATIONAL} "Instalar solo para &usuario actual"
LangString Installer_CurrentUserOption ${LANG_ITALIAN} "Installa solo per utente attuale"
LangString Installer_CurrentUserOption ${LANG_PORTUGUESE} "Instalar somente para &usuário atual"
LangString Installer_CurrentUserOption ${LANG_PORTUGUESEBR} "Instalar somente para o &usuário atual"
LangString Installer_CurrentUserOption ${LANG_RUSSIAN} "Установить только для &текущего пользователя"
LangString Installer_CurrentUserOption ${LANG_SIMPCHINESE} "仅为当前用户安装(&C)"
LangString Installer_CurrentUserOption ${LANG_TRADCHINESE} "僅為目前使用者安裝 (&C)"
LangString Installer_CurrentUserOption ${LANG_JAPANESE} "現在のユーザーのみにインストール(&C)"
LangString Installer_CurrentUserOption ${LANG_KOREAN} "&현재 사용자만 설치"
LangString Installer_CurrentUserOption ${LANG_DUTCH} "Alleen voor &huidige gebruiker installeren"
LangString Installer_CurrentUserOption ${LANG_POLISH} "Zainstaluj tylko dla &bieżącego użytkownika"
LangString Installer_CurrentUserOption ${LANG_CZECH} "Nainstalovat pouze pro a&ktuálního uživatele"
LangString Installer_CurrentUserOption ${LANG_SWEDISH} "Installera enbart för &nuvarande användare"
LangString Installer_CurrentUserOption ${LANG_DANISH} "Installér kun for &nuværende bruger"
LangString Installer_CurrentUserOption ${LANG_NORWEGIAN} "Installer bare for &gjeldende bruker"
LangString Installer_CurrentUserOption ${LANG_FINNISH} "Asenna vain &nykyiselle käyttäjälle"
LangString Installer_CurrentUserOption ${LANG_GREEK} "Εγκατάσταση μόνο για τον &τρέχοντα χρήστη"
LangString Installer_CurrentUserOption ${LANG_HUNGARIAN} "Telepítés csak az a&ktuális felhasználónak"
LangString Installer_CurrentUserOption ${LANG_ROMANIAN} "Instalare doar pentru utilizatorul &curent"
LangString Installer_CurrentUserOption ${LANG_TURKISH} "Yalnızca &geçerli kullanıcı için yükle"
LangString Installer_CurrentUserOption ${LANG_UKRAINIAN} "Встановити лише для &поточного користувача"
LangString Installer_CurrentUserOption ${LANG_ARABIC} "التثبيت للمستخدم ال&حالي فقط"
LangString Installer_CurrentUserOption ${LANG_HEBREW} "התקן עבור המשתמש ה&נוכחי בלבד"
LangString Installer_CurrentUserOption ${LANG_THAI} "ติดตั้งสำหรับผู้ใช้ปัจจุบันเท่านั้น (&C)"
LangString Installer_CurrentUserOption ${LANG_VIETNAMESE} "Chỉ cài đặt cho người dùng &hiện tại"
LangString Installer_CurrentUserOption ${LANG_INDONESIAN} "Instal untuk pengguna saat ini sa&ja"
LangString Installer_CurrentUserOption ${LANG_BULGARIAN} "Инсталиране само за &текущия потребител"
LangString Installer_CurrentUserOption ${LANG_CROATIAN} "Instaliraj samo za &trenutnog korisnika"
LangString Installer_CurrentUserOption ${LANG_SLOVAK} "Inštalovať iba pre a&ktuálneho používateľa"
LangString Installer_CurrentUserOption ${LANG_SLOVENIAN} "Namesti samo za &trenutnega uporabnika"

LangString Installer_CurrentUserDescription ${LANG_ENGLISH} "Recommended. The application will only be available for your user account."
LangString Installer_CurrentUserDescription ${LANG_FRENCH} "Recommandé. L'application ne sera disponible que pour votre compte utilisateur."
LangString Installer_CurrentUserDescription ${LANG_GERMAN} "Empfohlen. Die Anwendung wird nur für Ihr Benutzerkonto verfügbar sein."
LangString Installer_CurrentUserDescription ${LANG_SPANISHINTERNATIONAL} "Recomendado. La aplicación sólo estará disponible para su cuenta de usuario."
LangString Installer_CurrentUserDescription ${LANG_ITALIAN} "Consigliato. L'applicazione sarà disponibile solo per il proprio account utente."
LangString Installer_CurrentUserDescription ${LANG_PORTUGUESE} "Recomendado. O aplicativo estará disponível apenas para sua conta de usuário."
LangString Installer_CurrentUserDescription ${LANG_PORTUGUESEBR} "Recomendado. O aplicativo ficará disponível apenas para a sua conta de usuário."
LangString Installer_CurrentUserDescription ${LANG_RUSSIAN} "Рекомендуется. Приложение будет доступно только для вашей учётной записи."
LangString Installer_CurrentUserDescription ${LANG_SIMPCHINESE} "推荐。该应用程序仅对您的用户帐户可用。"
LangString Installer_CurrentUserDescription ${LANG_TRADCHINESE} "建議。此應用程式僅供您的使用者帳戶使用。"
LangString Installer_CurrentUserDescription ${LANG_JAPANESE} "推奨。アプリケーションは現在のユーザーアカウントでのみ使用できます。"
LangString Installer_CurrentUserDescription ${LANG_KOREAN} "권장됨. 응용 프로그램은 현재 사용자 계정에서만 사용할 수 있습니다."
LangString Installer_CurrentUserDescription ${LANG_DUTCH} "Aanbevolen. De toepassing is alleen beschikbaar voor uw gebruikersaccount."
LangString Installer_CurrentUserDescription ${LANG_POLISH} "Zalecane. Aplikacja będzie dostępna tylko dla Twojego konta użytkownika."
LangString Installer_CurrentUserDescription ${LANG_CZECH} "Doporučeno. Aplikace bude dostupná pouze pro váš uživatelský účet."
LangString Installer_CurrentUserDescription ${LANG_SWEDISH} "Rekommenderat. Applikationen blir enbart tillgänglig för ditt användarkonto."
LangString Installer_CurrentUserDescription ${LANG_DANISH} "Anbefalet. Applikationen vil kun være tilgængelig for din brugerkonto."
LangString Installer_CurrentUserDescription ${LANG_NORWEGIAN} "Anbefalt. Applikasjonen vil bare være tilgjengelig for din brukerkonto."
LangString Installer_CurrentUserDescription ${LANG_FINNISH} "Suositeltu. Sovellus on käytettävissä vain omalle käyttäjätilillesi."
LangString Installer_CurrentUserDescription ${LANG_GREEK} "Συνιστάται. Η εφαρμογή θα είναι διαθέσιμη μόνο για τον λογαριασμό χρήστη σας."
LangString Installer_CurrentUserDescription ${LANG_HUNGARIAN} "Ajánlott. Az alkalmazás csak az Ön felhasználói fiókja számára lesz elérhető."
LangString Installer_CurrentUserDescription ${LANG_ROMANIAN} "Recomandat. Aplicația va fi disponibilă doar pentru contul dvs. de utilizator."
LangString Installer_CurrentUserDescription ${LANG_TURKISH} "Önerilir. Uygulama yalnızca sizin kullanıcı hesabınız için kullanılabilir olacaktır."
LangString Installer_CurrentUserDescription ${LANG_UKRAINIAN} "Рекомендовано. Програма буде доступна лише для вашого облікового запису."
LangString Installer_CurrentUserDescription ${LANG_ARABIC} "مستحسن. سيكون التطبيق متاحاً لحساب المستخدم الخاص بك فقط."
LangString Installer_CurrentUserDescription ${LANG_HEBREW} "מומלץ. האפליקציה תהיה זמינה רק עבור חשבון המשתמש שלך."
LangString Installer_CurrentUserDescription ${LANG_THAI} "แนะนำ แอปพลิเคชันจะพร้อมใช้งานสำหรับบัญชีผู้ใช้ของคุณเท่านั้น"
LangString Installer_CurrentUserDescription ${LANG_VIETNAMESE} "Được khuyến nghị. Ứng dụng sẽ chỉ khả dụng cho tài khoản người dùng của bạn."
LangString Installer_CurrentUserDescription ${LANG_INDONESIAN} "Disarankan. Aplikasi hanya akan tersedia untuk akun pengguna Anda."
LangString Installer_CurrentUserDescription ${LANG_BULGARIAN} "Препоръчително. Приложението ще бъде достъпно само за вашия потребителски акаунт."
LangString Installer_CurrentUserDescription ${LANG_CROATIAN} "Preporučeno. Aplikacija će biti dostupna samo za vaš korisnički račun."
LangString Installer_CurrentUserDescription ${LANG_SLOVAK} "Odporúčané. Aplikácia bude dostupná iba pre váš používateľský účet."
LangString Installer_CurrentUserDescription ${LANG_SLOVENIAN} "Priporočeno. Aplikacija bo na voljo samo za vaš uporabniški račun."

LangString Installer_AllUsersOption ${LANG_ENGLISH} "Install for &all users (requires administrator privileges)"
LangString Installer_AllUsersOption ${LANG_FRENCH} "Installer pour &tous les utilisateurs (nécessite des privilèges d'administrateur)"
LangString Installer_AllUsersOption ${LANG_GERMAN} "Für &alle Benutzer installieren (erfordert Administratorrechte)"
LangString Installer_AllUsersOption ${LANG_SPANISHINTERNATIONAL} "Instalar para &todos los usuarios (requiere privilegios de administrador)"
LangString Installer_AllUsersOption ${LANG_ITALIAN} "Installa per &tutti gli utenti (richiede privilegi di amministratore)"
LangString Installer_AllUsersOption ${LANG_PORTUGUESE} "Instalar para &todos os usuários (requer privilégios de administrador)"
LangString Installer_AllUsersOption ${LANG_PORTUGUESEBR} "Instalar para &todos os usuários (requer privilégios de administrador)"
LangString Installer_AllUsersOption ${LANG_RUSSIAN} "Установить для &всех пользователей (требуются права администратора)"
LangString Installer_AllUsersOption ${LANG_SIMPCHINESE} "为所有用户安装（需要管理员权限）(&A)"
LangString Installer_AllUsersOption ${LANG_TRADCHINESE} "為所有使用者安裝（需要系統管理員權限）(&A)"
LangString Installer_AllUsersOption ${LANG_JAPANESE} "すべてのユーザー向けにインストール（管理者権限が必要）(&A)"
LangString Installer_AllUsersOption ${LANG_KOREAN} "&모든 사용자용 설치 (관리자 권한 필요)"
LangString Installer_AllUsersOption ${LANG_DUTCH} "Installeren voor &alle gebruikers (vereist beheerdersbevoegdheden)"
LangString Installer_AllUsersOption ${LANG_POLISH} "Zainstaluj dla &wszystkich użytkowników (wymaga uprawnień administratora)"
LangString Installer_AllUsersOption ${LANG_CZECH} "Nainstalovat pro &všechny uživatele (vyžaduje oprávnění správce)"
LangString Installer_AllUsersOption ${LANG_SWEDISH} "Installera för &alla användare (kräver administratörsbehörigheter)"
LangString Installer_AllUsersOption ${LANG_DANISH} "Installér for &alle brugere (kræver administratorrettigheder)"
LangString Installer_AllUsersOption ${LANG_NORWEGIAN} "Installer for &alle brukere (krever administratorrettigheter)"
LangString Installer_AllUsersOption ${LANG_FINNISH} "Asenna &kaikille käyttäjille (vaatii järjestelmänvalvojan oikeudet)"
LangString Installer_AllUsersOption ${LANG_GREEK} "Εγκατάσταση για ό&λους τους χρήστες (απαιτεί δικαιώματα διαχειριστή)"
LangString Installer_AllUsersOption ${LANG_HUNGARIAN} "Telepítés &minden felhasználónak (rendszergazdai jogosultságok szükségesek)"
LangString Installer_AllUsersOption ${LANG_ROMANIAN} "Instalare pentru &toți utilizatorii (necesită privilegii de administrator)"
LangString Installer_AllUsersOption ${LANG_TURKISH} "&Tüm kullanıcılar için yükle (yönetici ayrıcalıkları gerektirir)"
LangString Installer_AllUsersOption ${LANG_UKRAINIAN} "Встановити для &всіх користувачів (потрібні права адміністратора)"
LangString Installer_AllUsersOption ${LANG_ARABIC} "التثبيت ل&جميع المستخدمين (يتطلب صلاحيات المسؤول)"
LangString Installer_AllUsersOption ${LANG_HEBREW} "התקן עבור &כל המשתמשים (דורש הרשאות מנהל)"
LangString Installer_AllUsersOption ${LANG_THAI} "ติดตั้งสำหรับผู้ใช้ทุกคน (ต้องการสิทธิ์ผู้ดูแลระบบ) (&A)"
LangString Installer_AllUsersOption ${LANG_VIETNAMESE} "Cài đặt cho &tất cả người dùng (yêu cầu quyền quản trị viên)"
LangString Installer_AllUsersOption ${LANG_INDONESIAN} "Instal untuk &semua pengguna (memerlukan hak istimewa administrator)"
LangString Installer_AllUsersOption ${LANG_BULGARIAN} "Инсталиране за &всички потребители (изисква администраторски права)"
LangString Installer_AllUsersOption ${LANG_CROATIAN} "Instaliraj za &sve korisnike (zahtijeva administratorske ovlasti)"
LangString Installer_AllUsersOption ${LANG_SLOVAK} "Inštalovať pre &všetkých používateľov (vyžaduje oprávnenia správcu)"
LangString Installer_AllUsersOption ${LANG_SLOVENIAN} "Namesti za &vse uporabnike (zahteva skrbniške pravice)"

LangString Installer_AllUsersDescription ${LANG_ENGLISH} "The application will be available for all users on this computer."
LangString Installer_AllUsersDescription ${LANG_FRENCH} "L'application sera disponible pour tous les utilisateurs de cet ordinateur."
LangString Installer_AllUsersDescription ${LANG_GERMAN} "Die Anwendung wird für alle Benutzer auf diesem Computer verfügbar sein."
LangString Installer_AllUsersDescription ${LANG_SPANISHINTERNATIONAL} "La aplicación estará disponible para todos los usuarios de esta computadora."
LangString Installer_AllUsersDescription ${LANG_ITALIAN} "L'applicazione sarà disponibile per tutti gli utenti di questo computer."
LangString Installer_AllUsersDescription ${LANG_PORTUGUESE} "O aplicativo estará disponível para todos os usuários deste computador."
LangString Installer_AllUsersDescription ${LANG_PORTUGUESEBR} "O aplicativo ficará disponível para todos os usuários deste computador."
LangString Installer_AllUsersDescription ${LANG_RUSSIAN} "Приложение будет доступно для всех пользователей этого компьютера."
LangString Installer_AllUsersDescription ${LANG_SIMPCHINESE} "该应用程序将对此计算机上的所有用户可用。"
LangString Installer_AllUsersDescription ${LANG_TRADCHINESE} "此應用程式將可供此電腦上的所有使用者使用。"
LangString Installer_AllUsersDescription ${LANG_JAPANESE} "このコンピューターのすべてのユーザーがアプリケーションを使用できます。"
LangString Installer_AllUsersDescription ${LANG_KOREAN} "이 컴퓨터의 모든 사용자가 응용 프로그램을 사용할 수 있습니다."
LangString Installer_AllUsersDescription ${LANG_DUTCH} "De toepassing is beschikbaar voor alle gebruikers op deze computer."
LangString Installer_AllUsersDescription ${LANG_POLISH} "Aplikacja będzie dostępna dla wszystkich użytkowników tego komputera."
LangString Installer_AllUsersDescription ${LANG_CZECH} "Aplikace bude dostupná pro všechny uživatele na tomto počítači."
LangString Installer_AllUsersDescription ${LANG_SWEDISH} "Applikationen blir tillgänglig för alla användare på denna dator."
LangString Installer_AllUsersDescription ${LANG_DANISH} "Applikationen vil være tilgængelig for alle brugere på denne computer."
LangString Installer_AllUsersDescription ${LANG_NORWEGIAN} "Applikasjonen vil være tilgjengelig for alle brukere på denne datamaskinen."
LangString Installer_AllUsersDescription ${LANG_FINNISH} "Sovellus on kaikkien tämän tietokoneen käyttäjien käytettävissä."
LangString Installer_AllUsersDescription ${LANG_GREEK} "Η εφαρμογή θα είναι διαθέσιμη για όλους τους χρήστες σε αυτόν τον υπολογιστή."
LangString Installer_AllUsersDescription ${LANG_HUNGARIAN} "Az alkalmazás elérhető lesz a számítógép összes felhasználója számára."
LangString Installer_AllUsersDescription ${LANG_ROMANIAN} "Aplicația va fi disponibilă pentru toți utilizatorii de pe acest computer."
LangString Installer_AllUsersDescription ${LANG_TURKISH} "Uygulama bu bilgisayardaki tüm kullanıcılar için kullanılabilir olacaktır."
LangString Installer_AllUsersDescription ${LANG_UKRAINIAN} "Програма буде доступна для всіх користувачів цього комп'ютера."
LangString Installer_AllUsersDescription ${LANG_ARABIC} "سيكون التطبيق متاحاً لجميع المستخدمين على هذا الكمبيوتر."
LangString Installer_AllUsersDescription ${LANG_HEBREW} "האפליקציה תהיה זמינה לכל המשתמשים במחשב זה."
LangString Installer_AllUsersDescription ${LANG_THAI} "แอปพลิเคชันจะพร้อมใช้งานสำหรับผู้ใช้ทุกคนบนคอมพิวเตอร์เครื่องนี้"
LangString Installer_AllUsersDescription ${LANG_VIETNAMESE} "Ứng dụng sẽ khả dụng cho tất cả người dùng trên máy tính này."
LangString Installer_AllUsersDescription ${LANG_INDONESIAN} "Aplikasi akan tersedia untuk semua pengguna di komputer ini."
LangString Installer_AllUsersDescription ${LANG_BULGARIAN} "Приложението ще бъде достъпно за всички потребители на този компютър."
LangString Installer_AllUsersDescription ${LANG_CROATIAN} "Aplikacija će biti dostupna svim korisnicima na ovom računalu."
LangString Installer_AllUsersDescription ${LANG_SLOVAK} "Aplikácia bude dostupná pre všetkých používateľov tohto počítača."
LangString Installer_AllUsersDescription ${LANG_SLOVENIAN} "Aplikacija bo na voljo vsem uporabnikom tega računalnika."

LangString Installer_AdminRequiredDetailed ${LANG_ENGLISH} "Administrator privileges are required to install for all users.$\n$\nPlease either:$\n- Choose 'Install for current user only', or$\n- Run this installer as administrator"
LangString Installer_AdminRequiredDetailed ${LANG_FRENCH} "Des privilèges d'administrateur sont requis pour installer pour tous les utilisateurs.$\n$\nVeuillez :$\n- Choisir « Installer pour l'utilisateur actuel uniquement », ou$\n- Exécuter ce programme d'installation en tant qu'administrateur"
LangString Installer_AdminRequiredDetailed ${LANG_GERMAN} "Für die Installation für alle Benutzer sind Administratorrechte erforderlich.$\n$\nBitte wählen Sie eine der folgenden Optionen:$\n- „Nur für aktuellen Benutzer installieren$\" wählen, oder$\n- Dieses Installationsprogramm als Administrator ausführen"
LangString Installer_AdminRequiredDetailed ${LANG_SPANISHINTERNATIONAL} "Se requieren privilegios de administrador para realizar la instalación para todos los usuarios.$\n$\nPor favor:$\n- Elija 'Instalar solo para el usuario actual', o$\n- Ejecute este instalador como administrador."
LangString Installer_AdminRequiredDetailed ${LANG_ITALIAN} "Per installare per tutti gli utenti sono necessari i privilegi di amministratore.$\n$\nSceglie una delle seguenti opzioni:$\n- Seleziona $\"Installa solo per utente attuale$\", o$\n- Esegui il programma di installazione come amministratore"
LangString Installer_AdminRequiredDetailed ${LANG_PORTUGUESE} "São necessários privilégios de administrador para instalação para todos os usuários.$\n$\nPor favor:$\n- Escolha 'Instalar apenas para o usuário atual' ou$\n- Execute este instalador como administrador"
LangString Installer_AdminRequiredDetailed ${LANG_PORTUGUESEBR} "São necessários privilégios de administrador para instalar para todos os usuários.$\n$\nPor favor, escolha uma das opções:$\n- Selecione 'Instalar somente para o usuário atual', ou$\n- Execute este instalador como administrador"
LangString Installer_AdminRequiredDetailed ${LANG_RUSSIAN} "Для установки для всех пользователей требуются права администратора.$\n$\nПожалуйста, выберите один из вариантов:$\n- Выберите «Установить только для текущего пользователя», или$\n- Запустите этот установщик от имени администратора"
LangString Installer_AdminRequiredDetailed ${LANG_SIMPCHINESE} "为所有用户安装需要管理员权限。$\n$\n请执行以下操作之一：$\n- 选择$\"仅为当前用户安装$\"，或$\n- 以管理员身份运行此安装程序"
LangString Installer_AdminRequiredDetailed ${LANG_TRADCHINESE} "安裝給所有使用者需要系統管理員權限。$\n$\n請選擇：$\n- 選擇「僅為目前使用者安裝」，或$\n- 以系統管理員身分執行此安裝程式"
LangString Installer_AdminRequiredDetailed ${LANG_JAPANESE} "すべてのユーザー向けにインストールするには管理者権限が必要です。$\n$\n次のいずれかを選択してください:$\n- 「現在のユーザーのみにインストール」を選択する$\n- このインストーラーを管理者として実行する"
LangString Installer_AdminRequiredDetailed ${LANG_KOREAN} "모든 사용자를 위해 설치하려면 관리자 권한이 필요합니다.$\n$\n다음 중 하나를 선택하세요:$\n- '현재 사용자만 설치'를 선택하거나$\n- 이 설치 프로그램을 관리자로 실행하세요"
LangString Installer_AdminRequiredDetailed ${LANG_DUTCH} "Beheerdersbevoegdheden zijn vereist om voor alle gebruikers te installeren.$\n$\nKies een van de volgende opties:$\n- Kies 'Alleen voor huidige gebruiker installeren', of$\n- Voer dit installatieprogramma uit als beheerder"
LangString Installer_AdminRequiredDetailed ${LANG_POLISH} "Do instalacji dla wszystkich użytkowników wymagane są uprawnienia administratora.$\n$\nProszę:$\n- Wybrać „Zainstaluj tylko dla bieżącego użytkownika$\", lub$\n- Uruchomić instalator jako administrator"
LangString Installer_AdminRequiredDetailed ${LANG_CZECH} "Pro instalaci pro všechny uživatele jsou vyžadována oprávnění správce.$\n$\nProsím vyberte:$\n- Zvolte „Nainstalovat pouze pro aktuálního uživatele$\", nebo$\n- Spusťte tento instalační program jako správce"
LangString Installer_AdminRequiredDetailed ${LANG_SWEDISH} "Administratörsbehörigheter krävs för att installera för alla användare.$\n$\nVänligen välj:$\n- Välj 'Installera enbart för nuvarande användare', eller$\n- Kör detta installationsprogram som administratör"
LangString Installer_AdminRequiredDetailed ${LANG_DANISH} "Administratorrettigheder kræves for at installere for alle brugere.$\n$\nVælg venligst:$\n- Vælg 'Installér kun for nuværende bruger', eller$\n- Kør dette installationsprogram som administrator"
LangString Installer_AdminRequiredDetailed ${LANG_NORWEGIAN} "Administratorrettigheter kreves for å installere for alle brukere.$\n$\nVennligst gjør ett av følgende:$\n- Velg 'Installer bare for gjeldende bruker', eller$\n- Kjør dette installasjonsprogrammet som administrator"
LangString Installer_AdminRequiredDetailed ${LANG_FINNISH} "Järjestelmänvalvojan oikeudet vaaditaan asennukseen kaikille käyttäjille.$\n$\nOle hyvä ja joko:$\n- Valitse 'Asenna vain nykyiselle käyttäjälle', tai$\n- Suorita tämä asennusohjelma järjestelmänvalvojana"
LangString Installer_AdminRequiredDetailed ${LANG_GREEK} "Απαιτούνται δικαιώματα διαχειριστή για εγκατάσταση για όλους τους χρήστες.$\n$\nΠαρακαλώ είτε:$\n- Επιλέξτε 'Εγκατάσταση μόνο για τον τρέχοντα χρήστη', ή$\n- Εκτελέστε αυτό το πρόγραμμα εγκατάστασης ως διαχειριστής"
LangString Installer_AdminRequiredDetailed ${LANG_HUNGARIAN} "Az összes felhasználó számára történő telepítéshez rendszergazdai jogosultságok szükségesek.$\n$\nKérjük, válasszon:$\n- Válassza a „Telepítés csak az aktuális felhasználónak$\" lehetőséget, vagy$\n- Futtassa a telepítőt rendszergazdaként"
LangString Installer_AdminRequiredDetailed ${LANG_ROMANIAN} "Sunt necesare privilegii de administrator pentru instalarea pentru toți utilizatorii.$\n$\nVă rugăm să:$\n- Alegeți „Instalare doar pentru utilizatorul curent$\", sau$\n- Rulați acest program de instalare ca administrator"
LangString Installer_AdminRequiredDetailed ${LANG_TURKISH} "Tüm kullanıcılar için yüklemek için yönetici ayrıcalıkları gereklidir.$\n$\nLütfen şunlardan birini yapın:$\n- 'Yalnızca geçerli kullanıcı için yükle' seçeneğini seçin veya$\n- Bu yükleyiciyi yönetici olarak çalıştırın"
LangString Installer_AdminRequiredDetailed ${LANG_UKRAINIAN} "Для встановлення для всіх користувачів потрібні права адміністратора.$\n$\nБудь ласка:$\n- Виберіть «Встановити лише для поточного користувача», або$\n- Запустіть цей інсталятор від імені адміністратора"
LangString Installer_AdminRequiredDetailed ${LANG_ARABIC} "يلزم وجود صلاحيات المسؤول للتثبيت لجميع المستخدمين.$\n$\nيرجى إما:$\n- اختيار 'التثبيت للمستخدم الحالي فقط'، أو$\n- تشغيل هذا المثبت كمسؤول"
LangString Installer_AdminRequiredDetailed ${LANG_HEBREW} "נדרשות הרשאות מנהל להתקנה עבור כל המשתמשים.$\n$\nאנא בחר אחת מהאפשרויות:$\n- בחר 'התקן עבור המשתמש הנוכחי בלבד', או$\n- הפעל תוכנית התקנה זו כמנהל"
LangString Installer_AdminRequiredDetailed ${LANG_THAI} "จำเป็นต้องมีสิทธิ์ผู้ดูแลระบบเพื่อติดตั้งสำหรับผู้ใช้ทุกคน$\n$\nกรุณาเลือก:$\n- เลือก 'ติดตั้งสำหรับผู้ใช้ปัจจุบันเท่านั้น' หรือ$\n- เรียกใช้ตัวติดตั้งนี้ในฐานะผู้ดูแลระบบ"
LangString Installer_AdminRequiredDetailed ${LANG_VIETNAMESE} "Cần quyền quản trị viên để cài đặt cho tất cả người dùng.$\n$\nVui lòng:$\n- Chọn 'Chỉ cài đặt cho người dùng hiện tại', hoặc$\n- Chạy trình cài đặt này với quyền quản trị viên"
LangString Installer_AdminRequiredDetailed ${LANG_INDONESIAN} "Hak istimewa administrator diperlukan untuk menginstal bagi semua pengguna.$\n$\nSilakan:$\n- Pilih 'Instal untuk pengguna saat ini saja', atau$\n- Jalankan penginstal ini sebagai administrator"
LangString Installer_AdminRequiredDetailed ${LANG_BULGARIAN} "За инсталирането за всички потребители са необходими администраторски права.$\n$\nМоля, изберете една от следните опции:$\n- Изберете „Инсталиране само за текущия потребител$\", или$\n- Стартирайте този инсталатор като администратор"
LangString Installer_AdminRequiredDetailed ${LANG_CROATIAN} "Za instalaciju za sve korisnike potrebne su administratorske ovlasti.$\n$\nMolimo odaberite jednu od opcija:$\n- Odaberite „Instaliraj samo za trenutnog korisnika$\", ili$\n- Pokrenite ovaj instalacijski program kao administrator"
LangString Installer_AdminRequiredDetailed ${LANG_SLOVAK} "Pre inštaláciu pre všetkých používateľov sú vyžadované oprávnenia správcu.$\n$\nProsím vyberte jednu z možností:$\n- Zvoľte „Inštalovať iba pre aktuálneho používateľa$\", alebo$\n- Spustite tento inštalátor ako správca"
LangString Installer_AdminRequiredDetailed ${LANG_SLOVENIAN} "Za namestitev za vse uporabnike so potrebne skrbniške pravice.$\n$\nProsimo, izberite eno od možnosti:$\n- Izberite „Namesti samo za trenutnega uporabnika$\", ali$\n- Zaženite ta namestitveni program kot skrbnik"
